Infra [CDOND-C3]: Update Circle CI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,46 @@
 version: 2.1
 
+orbs:
+  slack: circleci/slack@4.12.5
+
+commands:
+  destroy-environment:
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    parameters:
+      workflow-id:
+        default: ""
+        type: string
+        description: The unique ID of the workflow to identify the environment stacks.
+    steps:
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+            # Add code to destroy the cloudformation stacks based on the provided workflow-id
+            # For example, you can use AWS CLI to delete stacks:
+            aws s3 rm s3://udapeople-<<parameters.workflow-id>> --recursive || true
+            aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow-id>>
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflow-id>>
+
+  revert-migrations:
+    description: Revert the last migration
+    parameters:
+      workflow-id:
+        type: string
+    steps:
+      - run:
+          name: Revert migrations
+          when: on_fail
+          command: |
+            SUCCESS=$(curl --insecure  https://kvdb.io/Rr9w4xHEBnyxqKqpAJGQmJ/migration_<< parameters.workflow-id >>)
+            # Logic for reverting the database state
+            if (( $SUCCESS == 1 ));
+            then
+              cd ~/project/backend
+              npm install
+              npm run migration:revert
+            fi
+
 jobs:
   build-frontend:
     docker:
@@ -39,29 +80,23 @@ jobs:
     docker:
       # Docker image here
       - image: circleci/node:13.8.0
+    # working_directory: ~/project/frontend
     steps:
       # Checkout code from git
       - checkout
       # Restore from cache
       - restore_cache:
-          keys:
-            - v1-dependencies-{{ checksum "package.json" }}
-            - v1-dependencies-
+          keys: [frontend-test]
       # Your job code here
       # Install Node.js packages
       - run: |
           cd frontend
           npm install
+          npm run test
       # Save dependencies to cache
       - save_cache:
-          paths:
-            - node_modules
-          key: v1-dependencies-{{ checksum "package.json" }}
-      # Run tests using Jest
-      - run:
-          command: |
-            cd frontend
-            npm run test
+          paths: [frontend/node_modules]
+          key: frontend-test
 
   test-backend:
     docker:
@@ -72,22 +107,355 @@ jobs:
       - checkout
       # Restore from cache
       - restore_cache:
-          keys:
-            - v1-dependencies-{{ checksum "package.json" }}
-            - v1-dependencies-
+          keys: [backend-test]
       # Your job code here
       # Install Node.js packages
       - run: |
           cd backend
           npm install
+          npm run test
       # Save dependencies to cache
       - save_cache:
-          paths:
-            - node_modules
-          key: v1-dependencies-{{ checksum "package.json" }}
-      # Run tests using Jest
+          paths: [backend/node_modules]
+          key: backend-test
+
+  scan-frontend:
+    docker:
+      # Docker image here
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      # Restore from cache
+      - restore_cache:
+          keys: [frontend-scan]
+      # Your job code here
       - run: |
-          npm test
+          cd frontend
+          npm install
+          ## npm install oauth-sign@^0.9.0
+          npm audit fix --audit-level=critical --force
+          ## If the "npm audit fix" command above could not fix all critical vulnerabilities, try “npm audit fix --force” again
+          npm audit fix --force
+          npm audit --audit-level=critical
+      # Save dependencies to cache
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-scan
+      - slack/notify:
+          channel: C05TPQKC9NW
+          event: fail
+          template: basic_fail_1
+          debug: true
+
+  scan-backend:
+    docker:
+      # Docker image here
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      # Restore from cache
+      - restore_cache:
+          keys: [backend-scan]
+      # Your job code here
+      - run: |
+          cd backend
+          npm install
+          ## npm install oauth-sign@^0.9.0
+          npm audit fix --audit-level=critical --force
+          ## If the "npm audit fix" command above could not fix all critical vulnerabilities, try “npm audit fix --force” again
+          npm audit fix --force
+          npm audit --audit-level=critical
+      # Save dependencies to cache
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-scan
+
+  configure-infrastructure:
+    docker:
+      # Docker image here that supports Ansible
+      - image: python:3.7-alpine3.11
+    steps:
+      # Checkout code from git
+      - checkout
+      # Add ssh keys with fingerprint
+      - add_ssh_keys:
+          fingerprints:
+            - "08:07:23:c6:40:13:5b:07:30:db:e4:28:fa:80:2d:e2"
+      # attach workspace
+      - attach_workspace:
+          at: ~/project
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update ansible
+            pip install --upgrade pip
+            pip install awscli
+      - run:
+          name: Configure server
+          command: |
+            cd .circleci/ansible
+            cat inventory.txt
+            ansible-playbook -v -i inventory.txt configure-server.yml
+      - destroy-environment:
+          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
+
+  deploy-infrastructure:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      - run:
+          name: Install tar and gzip
+          command: |
+            # Update package list and install tar and gzip
+            yum update -y
+            yum install -y tar gzip curl
+      - run:
+          name: Ensure backend infrastructure exist
+          command: |
+            aws cloudformation deploy \
+            --template-file .circleci/files/backend.yml \
+            --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+            --tags project=udapeople
+      - run:
+          name: Ensure frontend infrastructure exist
+          command: |
+            aws cloudformation deploy \
+            --template-file .circleci/files/frontend.yml \
+            --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+            --tags project=udapeople
+      - run:
+          name: Add the EC2 instance IP to the Ansible inventory
+          command: |
+            BACKEND_IP=$(aws cloudformation describe-stacks \
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query "Stacks[0].Outputs[?OutputKey=='BackendIP'].OutputValue" \
+              --output text)
+            echo $BACKEND_IP >> .circleci/ansible/inventory.txt
+            cat .circleci/ansible/inventory.txt
+      - persist_to_workspace:
+          root: ~/project
+          paths:
+            - .circleci/ansible/inventory.txt
+      - destroy-environment:
+          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - slack/notify:
+          channel: C05TPQKC9NW
+          event: fail
+          template: basic_fail_1
+
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: cimg/node:14.21.3
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            ## Run and save the migration output
+            npm run migrations > migrations_dump.txt
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+              then
+              # If you are using kvdb.io, generate the bucket ID "Rr9w4xHEBnyxqKqpAJGQmJ" in your local terminal first
+              curl https://kvdb.io/Rr9w4xHEBnyxqKqpAJGQmJ/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              fi
+        # Here's where you will add some code to rollback on failure
+      - destroy-environment:
+          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"
+      - revert-migrations:
+          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"
+
+  deploy-frontend:
+    docker:
+      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            yum update -y
+            yum install -y tar gzip
+            # Install Node.js and npm
+            curl -sL https://rpm.nodesource.com/setup_14.x | bash -
+            yum install -y nodejs
+      - attach_workspace:
+          at: ~/project
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(cat .circleci/ansible/inventory.txt | grep '^\[web\]' -A 1 | tail -n 1 | xargs)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment:
+          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"
+
+  deploy-backend:
+    docker:
+      # Docker image here that supports Ansible
+      - image: python:3.7-alpine3.11
+    steps:
+      # Checkout code from git
+      - checkout
+      # Add ssh keys with fingerprint
+      - add_ssh_keys:
+          fingerprints:
+            - "08:07:23:c6:40:13:5b:07:30:db:e4:28:fa:80:2d:e2"
+      # attach workspace
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update ansible nodejs npm tar gzip curl
+            pip install --upgrade pip
+            pip install awscli
+      - attach_workspace:
+          at: ~/project
+      - run:
+          name: Deploy backend
+          command: |
+            cd backend
+            npm i
+            npm run build
+            cd ..
+            ## Zip the directory
+            tar -C backend -czvf artifact.tar.gz .
+            cd .circleci/ansible
+            echo "Contents  of the inventory.txt file is -------"
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment:
+          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"
+      - revert-migrations:
+          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"
+
+  smoke-test:
+    docker:
+      # Lightweight Docker image
+      - image: alpine:latest
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update curl nodejs npm aws-cli tar
+      - attach_workspace:
+          at: ~/project
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(cat .circleci/ansible/inventory.txt | grep '^\[web\]' -A 1 | tail -n 1 | xargs)
+            echo "Backend IP: ${BACKEND_IP}"
+            echo "export BACKEND_IP=${BACKEND_IP}" >> $BASH_ENV
+      - run:
+          name: Backend smoke test.
+          command: |
+            source $BASH_ENV
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              return 0
+            else
+              return 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.ca-central-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+              # Change this to 0 after the job fails
+              return 0
+            else
+              return 1
+            fi
+      # Here's where you  will add some code to rollback on failure
+      - destroy-environment:
+          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"
+      - revert-migrations:
+          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"
+
+  cloudfront-update:
+    docker:
+      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      # - run:
+      #     name: Install dependencies
+      #     command: |
+      #       # your code here
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+            --template-file .circleci/files/cloudfront.yml \
+            --stack-name InitialStack \
+            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+            --tags project=udapeople
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment:
+          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"
+      - revert-migrations:
+          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"
+
+  cleanup:
+    docker:
+      # Docker image here
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Get old stack workflow id
+          command: |
+            ## Fetch the Old workflow ID
+            export OldWorkflowID=$(aws cloudformation \
+                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                      --no-paginate --output text)
+            echo OldWorkflowID: "${OldWorkflowID}"
+            ## Fetch the current workflow ID
+            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+            ## Fetch the stack names          
+            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+                      --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+            echo Stack names: "${STACKS[@]}"
+            ## Remove old stacks and files
+            if [[ "${STACKS[@]}" == "${OldWorkflowID}" ]]
+            then
+              echo "---------------------Delete Confirmed---------------------------------"
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            else
+              echo "---------------------Cannot Cleanup---------------------------------"
+            fi
 
 workflows:
   default:
@@ -98,3 +466,27 @@ workflows:
           requires: [build-frontend]
       - test-backend:
           requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
+          context: Slack
+      - scan-backend:
+          requires: [build-backend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [master]
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update:
+          requires: [smoke-test]
+      - cleanup:
+          requires: [cloudfront-update]
